"""Configuration management for Databricks Code Assist."""

import os
from pathlib import Path
from typing import Optional

import yaml

# Default configuration
DEFAULT_PORT = 4000
DEFAULT_MODEL = "claude-sonnet-4"

# Configuration paths
CONFIG_DIR = Path.home() / ".databricks-code-assist"
CONFIG_FILE = CONFIG_DIR / "config.yaml"
LITELLM_CONFIG_FILE = CONFIG_DIR / "litellm_config.yaml"
LOGS_DIR = CONFIG_DIR / "logs"

# Template configurations
LITELLM_CONFIG_TEMPLATE = """model_list:
  - model_name: {model}
    litellm_params:
      model: databricks/{model}
      api_key: {api_key}
      api_base: https://{host}/serving-endpoints
      max_tokens: 8192

litellm_settings:
  drop_params: false
  set_verbose: false
"""

CONTINUE_CONFIG_TEMPLATE = """name: Databricks-via-LiteLLM
version: 1.0.0
schema: v1

models:
  - name: Databricks-Claude-Sonnet-4
    provider: openai
    model: {model}
    apiBase: http://localhost:{port}/v1
    apiKey: dummy
    roles:
      - chat
      - edit
    defaultCompletionOptions:
      temperature: 0.7
      maxTokens: 8192
      topP: 0.9
"""

AIDER_CONFIG_TEMPLATE = """# Aider configuration for Databricks LLM integration
# Generated by databricks-code-assist

# Use OpenAI-compatible API endpoint (LiteLLM proxy)
openai-api-base: http://localhost:{port}/v1

# Set the model to use (openai/ prefix tells aider to use OpenAI-compatible API)
model: openai/{model}

# API key (can be any non-empty string for local proxy)
openai-api-key: not-needed

# Git settings
auto-commits: true
dirty-commits: true
attribute-author: false
attribute-committer: false

# Editor settings
editor: vim

# Display settings
pretty: true
stream: true
dark-mode: true
show-diffs: true
"""


def ensure_config_dir() -> None:
    """Ensure the configuration directory exists."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    LOGS_DIR.mkdir(parents=True, exist_ok=True)


def get_config() -> dict:
    """Load configuration from file."""
    if not CONFIG_FILE.exists():
        return {}
    with open(CONFIG_FILE) as f:
        return yaml.safe_load(f) or {}


def save_config(config: dict) -> None:
    """Save configuration to file."""
    ensure_config_dir()
    with open(CONFIG_FILE, "w") as f:
        yaml.dump(config, f, default_flow_style=False)


def get_databricks_credentials() -> tuple[Optional[str], Optional[str]]:
    """Get Databricks credentials from config or environment variables.

    Returns:
        Tuple of (host, api_key)
    """
    config = get_config()

    # Config file takes priority, then environment variables
    host = config.get("host") or os.environ.get("DATABRICKS_HOST")
    api_key = config.get("api_key") or os.environ.get("DATABRICKS_TOKEN")

    # Clean up host (remove https:// prefix and trailing slash)
    if host:
        host = host.replace("https://", "").replace("http://", "").rstrip("/")

    return host, api_key


def generate_litellm_config(
    host: str, api_key: str, model: str = DEFAULT_MODEL
) -> Path:
    """Generate LiteLLM configuration file.

    Args:
        host: Databricks workspace host
        api_key: Databricks API token
        model: Model name to use

    Returns:
        Path to the generated config file
    """
    ensure_config_dir()

    config_content = LITELLM_CONFIG_TEMPLATE.format(
        host=host,
        api_key=api_key,
        model=model,
    )

    with open(LITELLM_CONFIG_FILE, "w") as f:
        f.write(config_content)

    return LITELLM_CONFIG_FILE


def generate_continue_config(port: int = DEFAULT_PORT, model: str = DEFAULT_MODEL) -> Path:
    """Generate Continue.dev configuration file.

    Args:
        port: LiteLLM proxy port
        model: Model name to use

    Returns:
        Path to the generated config file
    """
    continue_dir = Path.home() / ".continue"
    continue_dir.mkdir(parents=True, exist_ok=True)
    continue_config_file = continue_dir / "config.yaml"

    config_content = CONTINUE_CONFIG_TEMPLATE.format(
        port=port,
        model=model,
    )

    with open(continue_config_file, "w") as f:
        f.write(config_content)

    return continue_config_file


def generate_aider_config(
    project_dir: Path, port: int = DEFAULT_PORT, model: str = DEFAULT_MODEL
) -> Path:
    """Generate Aider configuration file for a project.

    Args:
        project_dir: Project directory to create config in
        port: LiteLLM proxy port
        model: Model name to use

    Returns:
        Path to the generated config file
    """
    aider_config_file = project_dir / ".aider.conf.yml"

    config_content = AIDER_CONFIG_TEMPLATE.format(
        port=port,
        model=model,
    )

    with open(aider_config_file, "w") as f:
        f.write(config_content)

    return aider_config_file
