name: Databricks-via-LiteLLM
version: 1.0.0
schema: v1

models:
  - name: Claude-Sonnet-4
    provider: openai
    model: claude-sonnet-4  # Must match model_name in LiteLLM config
    apiBase: http://localhost:4000/v1  # LiteLLM proxy URL with /v1
    apiKey: dummy  # Any string works if no auth on LiteLLM
    roles:
      - chat
      - edit
#      - apply
#      - autocomplete #this will send a lot of requests, WARNING!!!
    defaultCompletionOptions:
      temperature: 0.7
      maxTokens: 8192
      topP: 0.9
