model_list:
  - model_name: claude-sonnet-4
    litellm_params:
      model: databricks/databricks-claude-sonnet-4
      api_key: ${WORKSPACE_API_TOKEN}
      api_base: https://${WORKSPACE_HOST}/serving-endpoints
      max_tokens: 8192

litellm_settings:
  drop_params: false
  set_verbose: true